fwf-api-animal-poc-dispatcher Developer
InternshipFWF/MateiColdea-fwf-api-animal-poc-dispatcher pull request #1
Opened 2023-08-22 06:33 UTC by mateicoldea

2023-08-22 08:39 UTC, AlexandraPertea requested changes
1. Please add process title, description & additional information to your project
![image](https://github.com/InternshipFWF/MateiColdea-fwf-api-animal-poc-dispatcher/assets/102737511/f8afa69c-f98e-4ea7-8bd4-2e4b2b40106d)
2. Please upgrade/downgrade dependencies to more stable ones
3. Update the logF_BusinessProcessName in Config accordingly
![image](https://github.com/InternshipFWF/MateiColdea-fwf-api-animal-poc-dispatcher/assets/102737511/aaf6cc10-ada3-4533-ab0f-e2b2bcff7749)
Also, it's not recommended to have whitespaces in your namings such as the below
![image](https://github.com/InternshipFWF/MateiColdea-fwf-api-animal-poc-dispatcher/assets/102737511/6a331bc0-9a36-469a-9e20-0743453d9b25)

2023-08-22 08:39 UTC, AlexandraPertea commented on ServiceLayer/ReadEmails.xaml
> +    <ui:GetOutlookMailMessages Account="{x:Null}" Filter="{x:Null}" FilterByMessageIds="{x:Null}" TimeoutMS="{x:Null}" DisplayName="Get Outlook Mails - Read Emails" GetAttachements="False" sap:Virtua
You can change the Top property of this activity to 1, to get the first unread email, since you already only take the one at index 0 later in your project.
Also, it's recommended as a best practice to mark the extracted email as read as well.

2023-08-22 08:39 UTC, AlexandraPertea commented on ServiceLayer/FilterEmails.xaml
> +<Activity mc:Ignorable="sap sap2010" x:Class="FilterEmails" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmln
This workflow doesn't belong to this layer, since you're not using outlook anymore.
It's better suited for the business layer.

2023-08-22 08:39 UTC, AlexandraPertea commented on ServiceLayer/FilterEmails.xaml
> +          <Throw DisplayName="Throw - Filter Emails" Exception="[New BusinessRuleException(&quot;Sender is not accepted&quot;)]" sap:VirtualizedContainerService.HintSize="434,92" sap2010:WorkflowView
Please don't hardcode exception messages - store them in Config.

2023-08-22 08:39 UTC, AlexandraPertea commented on Framework/GetTransactionData.xaml
> +    <ui:RetryScope DisplayName="Retry Get transaction item" sap:VirtualizedContainerService.HintSize="510,1052.6666666666667" sap2010:WorkflowViewState.IdRef="RetryScope_2" NumberOfRetries="[Cint(in_
You can remove this retry & try-catch - this is done because the Get Transaction Item activity (which is the default in REF) uses APIs and this approach is made to avoid any connectivity issues that may arise.

2023-08-22 08:39 UTC, AlexandraPertea commented on Framework/GetTransactionData.xaml
> +              <If Condition="[io_dt_TransactionData is Nothing AndAlso  in_Email.Attachments.Any AndAlso in_Email.Attachments(0).Name.Contains(&quot;.xlsx&quot;)]" DisplayName="If not initialised and
This verification should be done where you verified the sender, in a separate workflow.
You should also verify the name of the attachment, like it says in the PDD.

2023-08-22 08:39 UTC, AlexandraPertea commented on Framework/Process.xaml
> +        <Catch x:TypeArguments="ui:BusinessRuleException" sap:VirtualizedContainerService.HintSize="400,186" sap2010:WorkflowViewState.IdRef="Catch`1_1">
Everything you do in Process and results in a business exception is handled by REF in SetTransactionStatus.xaml -> Business Exception sequence. So you don't really need this Try Catch. Everything in Catch for BE should be in SetTransactionStatus -> Business Exception.

2023-08-22 11:25 UTC, AlexandraPertea requested changes

2023-08-22 11:25 UTC, AlexandraPertea commented on BusinessLayer/FilterEmails.xaml
> +    <If Condition="[EmailApproval AndAlso  out_Email.Attachments.Any AndAlso out_Email.Attachments(0).Name.Contains(&quot;.xlsx&quot;)]" DisplayName="If Approved Email - Filter Emails" sap:Virtualize
As I've mentioned, please make a separate workflow to check the file **name** and **extension**, exactly as in the case of the email sender.
Then, you won't need this If, because if everything goes well, a simple assign can do, since the data is correct.

2023-08-22 11:25 UTC, AlexandraPertea commented on Main.xaml
> +<Activity mc:Ignorable="sap sap2010" x:Class="Main" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities" xmlns:av="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:mc="http
Since you have a transition from Init to End Process for BREs, you should handle them in End Process.

2023-08-22 11:25 UTC, AlexandraPertea commented on Framework/GetTransactionData.xaml
> +          <ui:SaveMailAttachments Attachments="{x:Null}" DisplayName="Save Attachments - Get Transaction Data" ExcludeInlineAttachments="False" FolderPath="[in_Config(&quot;PathToSaveFile&quot;).ToSt
This save should be done in Init as well - check again the SDD.

2023-08-22 11:25 UTC, AlexandraPertea commented on ServiceLayer/ConvertToQueueItem.xaml
> +<Activity mc:Ignorable="sap sap2010" x:Class="ConvertToQueueItem" xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006
This should be in the data layer.

2023-08-22 11:25 UTC, AlexandraPertea commented on Framework/Process.xaml
> +                              <ui:AddQueueItem ServiceBaseAddress="{x:Null}" TimeoutMS="{x:Null}" DisplayName="Add Queue Item for multiple - Process" FolderPath="POC API Animal" sap:VirtualizedContai
Not done.

2023-08-23 06:10 UTC, mateicoldea commented on Framework/GetTransactionData.xaml
> +          <ui:SaveMailAttachments Attachments="{x:Null}" DisplayName="Save Attachments - Get Transaction Data" ExcludeInlineAttachments="False" FolderPath="[in_Config(&quot;PathToSaveFile&quot;).ToSt
<img width="245" alt="image" src="https://github.com/InternshipFWF/MateiColdea-fwf-api-animal-poc-dispatcher/assets/139752098/34025887-eefb-477a-931f-a037e4e2e66a">

2023-08-23 07:33 UTC, AlexandraPertea commented on Framework/GetTransactionData.xaml
> +          <ui:SaveMailAttachments Attachments="{x:Null}" DisplayName="Save Attachments - Get Transaction Data" ExcludeInlineAttachments="False" FolderPath="[in_Config(&quot;PathToSaveFile&quot;).ToSt
Which diagram is this? From which folder?

2023-08-24 09:33 UTC, AlexandraPertea approved these changes

2023-08-24 09:34 UTC, merged